# -*- coding: utf-8 -*-
"""QFHackathon_BorsukUlam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpm-YwX1Kfgz142FZe10aXdznsR2uAE-

# Borsuk–Ulam in the Carbon-Hedge Pipeline: what it gives, and what QUBO does (and doesn't) do

Companion to `antipodal_qaoa.py` in `LeonC2009/QFHackathon`. (The repo's file named `Borsuk Ulam Implementation example` is empty, so this builds on the B-U pieces in `antipodal_qaoa.py`.)

**The claim to test:** three different things are happening in this project, and they are easy to blur together.

| Piece | What it actually does | What it does *not* do |
|---|---|---|
| **Borsuk–Ulam** | Guarantees a *continuous* hedge exists (some exposure vector `w` with `f(w) = f(−w)`), and gives the discrete problem its antipodal (long↔short) symmetry | Find the discrete pairs; enforce neutrality in the optimiser |
| **QUBO** | Encodes the discrete problem as a function `E(v) = vᵀQv` | Search for anything. It is a table of numbers |
| **Solver** (brute force / annealing / QAOA) | Searches the 2²ᴺ bitstrings for low `E(v)` | Know anything about carbon or B-U |

The penalty weights inside `Q` (not the theorem) are what push net carbon toward zero in the optimiser. Each section below isolates one of these.

**Data note:** as in the repo file, prices/vols/correlations here are **synthetic**; emission factors are approximate EPA values.
"""

import itertools
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

np.set_printoptions(precision=4, suppress=True)

# Universe: pure fossil-energy futures (synthetic market data, from antipodal_qaoa.py)
ASSETS = ["Brent", "WTI", "HeatOil", "TTF Gas", "HH Gas", "API2 Coal"]
EF = np.array([74.5, 74.5, 74.0, 53.1, 53.1, 93.3])      # kg CO2 / MMBtu (approx. EPA)
CARBON = EF / EF.max()                                    # normalised to [0, 1]
MU = np.array([0.02, 0.02, 0.01, 0.03, 0.02, -0.01])      # synthetic expected carry
N = len(ASSETS)
K = 2                                                     # longs == shorts == K

VOL = np.array([0.30, 0.32, 0.30, 0.55, 0.50, 0.40])
CORR = np.array([
    [1.00, 0.95, 0.85, 0.45, 0.35, 0.40],
    [0.95, 1.00, 0.83, 0.43, 0.40, 0.38],
    [0.85, 0.83, 1.00, 0.42, 0.33, 0.37],
    [0.45, 0.43, 0.42, 1.00, 0.40, 0.70],
    [0.35, 0.40, 0.33, 0.40, 1.00, 0.30],
    [0.40, 0.38, 0.37, 0.70, 0.30, 1.00],
])
SIGMA = np.outer(VOL, VOL) * CORR
assert np.linalg.eigvalsh(SIGMA).min() > 0

print(dict(zip(ASSETS, CARBON.round(3))))

"""## Part 1. What Borsuk–Ulam actually gives: *existence* of a hedge

**Theorem (B-U).** For any continuous `f : Sⁿ → ℝⁿ` there is a point `w ∈ Sⁿ` with `f(w) = f(−w)`.

Think of `w` as a normalised exposure vector (long positive, short negative). `−w` is the same book with every long and short flipped, the **antipode**. Define `g(w) = f(w) − f(−w)`. Then `g(−w) = −g(w)`: `g` is **odd**. B-U says an odd map from `Sⁿ` to `ℝⁿ` must vanish somewhere, so a point with `f(w) = f(−w)` exists.

Two consequences worth seeing explicitly:

1. Only the **odd part** of `f` matters. Even quantities (e.g. variance `wᵀΣw`) satisfy `f(w) = f(−w)` automatically and drop out of `g`.
2. Carbon exposure `c·w` is purely odd, so `g(w) = 2 c·w`, and "`f(w) = f(−w)`" is exactly "net carbon = 0".

### 1a. The circle case (two assets: gas vs coal)
`n = 1`: a 1-D function on the circle. This is the intermediate-value theorem in disguise, and it's the demo in the repo.
"""

c_clean, c_dirty = 53.1 / 93.3, 1.0           # gas vs coal, normalised carbon
f = lambda t: c_clean * np.cos(t) + c_dirty * np.sin(t)   # net carbon of w = (cos t, sin t)
g = lambda t: f(t) - f(t + np.pi)                          # odd under t -> t + pi

# bisection on [0, pi]: g(t + pi) = -g(t), so g(0) and g(pi) have opposite signs -> root exists
lo, hi = 0.0, np.pi
assert np.sign(g(lo)) != np.sign(g(hi))
while hi - lo > 1e-12:
    mid = (lo + hi) / 2
    lo, hi = (mid, hi) if np.sign(g(mid)) == np.sign(g(lo)) else (lo, mid)
t_star = (lo + hi) / 2
w_star = np.array([np.cos(t_star), np.sin(t_star)])

print(f"theta* = {t_star:.4f} rad -> weights gas:coal = {w_star[0]:+.3f} : {w_star[1]:+.3f}")
print(f"net carbon at w*  = {f(t_star):+.2e}")
print(f"f(w*) - f(-w*)    = {g(t_star):+.2e}   (B-U: f(w) = f(-w))")

t = np.linspace(0, 2 * np.pi, 400)
fig, ax = plt.subplots(figsize=(7, 3.4))
ax.plot(t, f(t), label="f(t) = carbon of w(t)")
ax.plot(t, f(t + np.pi), "--", label="f(t + π) = carbon of antipode")
ax.axvline(t_star, color="k", lw=0.8); ax.axvline(t_star + np.pi, color="k", lw=0.8)
ax.axhline(0, color="gray", lw=0.5)
ax.set_xlabel("angle t"); ax.set_title("f(t) and f(t+π) cross where net carbon = 0"); ax.legend()
plt.tight_layout(); plt.show()

"""Note the root comes in an antipodal pair (`t*` and `t* + π`): the long-gas/short-coal book and its mirror. B-U never tells you *which* of the pair you want. That's a modelling choice (the "odd tilt" later on).

### 1b. A case where B-U is doing real work: nonlinear `f : S² → ℝ²`
For *linear* `f` the theorem is overkill: `f(w) = f(−w)` just means `Aw = 0`, which linear algebra already solves (rank–nullity). B-U earns its keep when exposure is **nonlinear**, e.g. market impact makes exposure grow faster than position size.

Below: 3 assets, two simultaneous exposures (carbon and a market-beta), each with a nonlinear odd part plus an even part (variance-like terms). B-U guarantees a `w ∈ S²` where *both* odd parts vanish, with no solving required to know it exists. We then find it numerically.
"""

c3 = np.array([CARBON[3], CARBON[0], CARBON[5]])      # TTF gas, Brent, coal
b3 = np.array([0.5, 1.0, 0.8])                        # synthetic market betas
S3 = SIGMA[np.ix_([3, 0, 5], [3, 0, 5])]

def F(w):
    # carbon exposure with nonlinear (odd) market-impact term + EVEN variance-like term
    carbon  = c3 @ (w + 0.7 * w * np.abs(w)) + 0.4 * (w @ S3 @ w)
    # beta exposure with nonlinear odd cubic term + EVEN gross-exposure term
    beta    = b3 @ (0.5 * w + w ** 3) + 0.2 * np.abs(w).sum()
    return np.array([carbon, beta])

def sphere(theta, phi):
    return np.array([np.sin(theta) * np.cos(phi), np.sin(theta) * np.sin(phi), np.cos(theta)])

G = lambda ang: F(sphere(*ang)) - F(-sphere(*ang))    # odd map S^2 -> R^2

rng = np.random.default_rng(1)
roots = []
for _ in range(60):
    sol, info, ier, _ = fsolve(G, [rng.uniform(0.2, 2.9), rng.uniform(0, 2 * np.pi)], full_output=True)
    if ier == 1 and np.linalg.norm(G(sol)) < 1e-9:
        w = sphere(*sol)
        # canonicalise the antipodal pair {w, -w} so we count each pair once
        w = w if (w[np.nonzero(np.abs(w) > 1e-9)[0][0]] > 0) else -w
        if not any(np.allclose(w, r, atol=1e-5) for r in roots):
            roots.append(w)

print(f"B-U guarantees at least one antipodal pair; found {len(roots)} distinct pair(s):\n")
for w in roots:
    print(f"  w = {w.round(4)}  (gas, Brent, coal)   |  F(w) - F(-w) = {(F(w) - F(-w)).round(12)}")
w = roots[0]
print("\nF(w)  =", F(w).round(5), "\nF(-w) =", F(-w).round(5), "  <- equal: the antipodal pair has the same exposures")

"""**What this section establishes:** in the continuous relaxation, a hedge with `f(w) = f(−w)` exists, even for nonlinear exposures, and that is a *guarantee*, not a search procedure. That's the genuine contribution of B-U, and it's the part a purely numerical optimiser can't give you: confidence the target isn't empty.

**What it doesn't establish:** anything about *discrete* positions (a whole number of contracts, K longs and K shorts). That's Part 2–4.

## Part 2. The discrete problem inherits the antipodal symmetry

Binary variables `v = [x₀..x_{N−1}, y₀..y_{N−1}]` with `xᵢ = 1` ⇒ long asset *i*, `yᵢ = 1` ⇒ short asset *i*. Net exposure `w = x − y ∈ {−1, 0, 1}ᴺ`.

The **antipodal map** is `A(x, y) = (y, x)`, i.e. `w → −w`.

In the QUBO, split the terms into:

* **even** (invariant under `A`): carbon balance `A·(c·w)²`, covariance `B·wᵀΣw`, cardinality, exclusivity
* **odd** (flip sign under `A`): carbon tilt `τ·c·w`, carry `−λ·μ·w`

Even terms ⇒ ground states come in antipodal pairs. Odd terms are the only thing that can choose between a pair.
"""

def build_qubo(A=10.0, B=1.0, P_card=4.0, P_excl=4.0, tau=0.0, lam=0.0, carbon=CARBON):
    '''
    A       carbon balance   A * (c.x - c.y)^2            [even]
    B       covariance       B * w^T Sigma w               [even]
    P_card  cardinality      P * [(sum x - K)^2 + (sum y - K)^2]   [even]
    P_excl  exclusivity      P * sum_i x_i y_i             [even]
    tau     carbon tilt      tau * c.w                      [odd]
    lam     carry reward    -lam * mu.w                     [odd]
    '''
    n = 2 * N
    D = np.hstack([np.eye(N), -np.eye(N)])      # w = D v
    Q = np.zeros((n, n)); offset = 0.0

    Q += A * D.T @ np.outer(carbon, carbon) @ D
    Q += B * D.T @ SIGMA @ D
    for block in (slice(0, N), slice(N, n)):
        Q[block, block] += P_card * np.ones((N, N))
        idx = np.arange(block.start, block.stop)
        Q[idx, idx] += -2 * P_card * K
        offset += P_card * K ** 2
    for i in range(N):
        Q[i, N + i] += P_excl / 2
        Q[N + i, i] += P_excl / 2
    gvec = tau * carbon - lam * MU
    Q[np.arange(n), np.arange(n)] += np.concatenate([gvec, -gvec])
    return Q, offset

# enumerate all 2^(2N) = 4096 bitstrings (MSB first, matching format(idx, '0nb'))
n = 2 * N
ALL = ((np.arange(1 << n)[:, None] >> np.arange(n - 1, -1, -1)) & 1).astype(float)
ANTI = ALL[:, list(range(N, n)) + list(range(N))]            # apply A: swap long <-> short halves

def energies(Q, offset, Z=ALL):
    return np.einsum("bi,ij,bj->b", Z, Q, Z) + offset

def decode(bits):
    bits = np.asarray(bits).astype(int)
    x, y = bits[:N], bits[N:]
    return ([ASSETS[i] for i in range(N) if x[i]],
            [ASSETS[i] for i in range(N) if y[i]],
            float(CARBON @ (x - y)))

Q_sym, off_sym = build_qubo(tau=0.0, lam=0.0)
E_sym  = energies(Q_sym, off_sym)
E_anti = energies(Q_sym, off_sym, ANTI)
print("Even terms only:   max |E(v) - E(A v)| over all 4096 states =", np.abs(E_sym - E_anti).max())

Q_odd, off_odd = build_qubo(tau=0.3, lam=0.5)
E_odd  = energies(Q_odd, off_odd)
E_odd_anti = energies(Q_odd, off_odd, ANTI)
print("With odd tilt/carry: max |E(v) - E(A v)| =", np.abs(E_odd - E_odd_anti).max(), " <- symmetry broken")

# ground states of the symmetric problem
order = np.argsort(E_sym)
e0 = E_sym[order[0]]
gs = [i for i in order if np.isclose(E_sym[i], e0)]
print(f"\nSymmetric problem: ground energy {e0:.4f}, {len(gs)} degenerate ground states (they come in antipodal pairs):")
for i in gs:
    L, S, nc = decode(ALL[i])
    print(f"  long={L!s:22} short={S!s:22} net_carbon={nc:+.3f}")

"""So the symmetry is real and checkable: `E(v) = E(Av)` to machine precision for the even terms. **This is the legitimate B-U-flavoured content of the discrete model:** the problem is `Z₂`-symmetric (the same group action B-U is about), and the odd terms are exactly the knobs that break it.

But notice what the QUBO has *not* done yet: nothing here found a pair. We evaluated all 4096 energies by brute force. That's Part 3.

## Part 3. QUBO is an encoding; the solver finds the pairs

`Q` is just a matrix. Handing it to different solvers returns the pairs. Below: exact brute force and a simple **classical simulated annealer** (no quantum anything) on the *same* `Q`.

On the symmetric problem the annealer lands on a random member of the degenerate set (including random choice within an antipodal pair), which is exactly what you'd expect if the solver, not the matrix, is making the pick.
"""

def _anneal_once(Qs, offset, sweeps, T0, T1, rng):
    n = Qs.shape[0]
    v = rng.integers(0, 2, n).astype(float)
    E = v @ Qs @ v + offset
    best_v, best_E = v.copy(), E
    for s in range(sweeps):
        T = T0 * (T1 / T0) ** (s / (sweeps - 1))
        for i in rng.permutation(n):
            d = 1 - 2 * v[i]                                   # +1 if 0->1, -1 if 1->0
            dE = d * (Qs[i, i] + 2 * (Qs[i] @ v - Qs[i, i] * v[i]))
            if dE <= 0 or rng.random() < np.exp(-dE / T):
                v[i] += d; E += dE
                if E < best_E - 1e-12:
                    best_v, best_E = v.copy(), E
    return best_v, best_E

def simulated_annealing(Q, offset, sweeps=300, T0=10.0, T1=0.1, restarts=5, seed=0):
    rng = np.random.default_rng(seed)
    Qs = (Q + Q.T) / 2
    runs = [_anneal_once(Qs, offset, sweeps, T0, T1, rng) for _ in range(restarts)]
    return min(runs, key=lambda r: r[1])

# --- symmetric problem: which ground state does each run pick?
from collections import Counter
picks, reached = Counter(), 0
for seed in range(40):
    v, E = simulated_annealing(Q_sym, off_sym, seed=seed)
    if np.isclose(E, e0, atol=1e-6):
        reached += 1
        L, S, nc = decode(v)
        picks[(tuple(L), tuple(S))] += 1
print(f"{reached}/40 annealing runs reached the exact ground energy {e0:.3f}. Which ground state each picked:")
for (L, S), cnt in picks.most_common():
    print(f"  {cnt:2d}x long={list(L)} short={list(S)}")

# --- odd terms on: the tilt picks one side, and every solver agrees
e_opt = E_odd.min(); i_opt = int(E_odd.argmin())
print("\nWith odd tilt/carry on:")
print("  brute force :", decode(ALL[i_opt])[:2], f"E={e_opt:.4f}")
agree = 0
for seed in range(20):
    v, E = simulated_annealing(Q_odd, off_odd, seed=seed)
    agree += int(np.isclose(E, e_opt, atol=1e-6))
print(f"  annealing   : {agree}/20 runs reach the exact optimum energy")

"""Same `Q`, different search algorithms, same answer (up to which degenerate state is returned). The QUBO is the *problem statement*. QAOA and quantum annealing are further solvers you could drop in here (optional QAOA cell at the end), and the speed-up claim, if there is one, belongs to the solver, not to the encoding or to B-U.

### 3b. What actually forces net carbon to ≈ 0? The penalty weight `A`, not the theorem
Ablation: keep the symmetric structure, switch on the economic (odd) carry term, and sweep the carbon-balance weight `A`. If B-U's antipodal structure were enforcing neutrality, `A = 0` would still give a hedged book. It doesn't.
"""

rows = []
for A_w in [0.0, 0.1, 1.0, 10.0, 100.0]:
    Qa, oa = build_qubo(A=A_w, tau=0.0, lam=1.0)               # carry on, no carbon tilt
    Ea = energies(Qa, oa)
    i = int(Ea.argmin())
    L, S, nc = decode(ALL[i])
    sym_gap = np.abs(Ea - energies(Qa, oa, ANTI)).max()
    rows.append((A_w, L, S, nc))
    print(f"A={A_w:6.1f}  long={L!s:20} short={S!s:20} net_carbon={nc:+.3f}")

fig, ax = plt.subplots(figsize=(6, 3))
ax.bar([str(r[0]) for r in rows], [abs(r[3]) for r in rows])
ax.set_xlabel("carbon-balance weight A"); ax.set_ylabel("|net carbon| of optimum")
ax.set_title("Neutrality comes from the penalty term")
plt.tight_layout(); plt.show()

"""With `A = 0` the optimiser ignores carbon entirely (it chases carry) and the book is not neutral, even though the antipodal symmetry of the even terms is still there. Net carbon only collapses once the `A·(c·w)²` penalty is large. That's the README's own point: the mechanism is the explicit penalty and is "independent of spheres".

## Part 4. Why the continuous guarantee doesn't transfer to the discrete problem

B-U gives a real-valued `w` with zero net carbon. Discrete positions (K longs, K shorts, unit weights) need not contain an exact zero. In the baseline data, exact zero *does* exist, but only because Brent/WTI have identical emission factors (and TTF/HH too), so long-Brent/short-WTI cancels trivially. Perturb the emission factors slightly and it disappears.
"""

# feasible set: exactly K longs, K shorts, never both on the same asset
x, y = ALL[:, :N], ALL[:, N:]
feasible = (x.sum(1) == K) & (y.sum(1) == K) & ((x * y).sum(1) == 0)
print(f"{feasible.sum()} feasible discrete books out of {len(ALL)}")

def best_discrete_carbon(c):
    nc = np.abs((x - y) @ c)
    nc[~feasible] = np.inf
    return nc.min(), int(nc.argmin())

m0, _ = best_discrete_carbon(CARBON)
print(f"\nBaseline emission factors:  min |net carbon| over feasible books = {m0:.4f}")

rng = np.random.default_rng(7)
for trial in range(3):
    c_pert = CARBON * (1 + rng.uniform(-0.06, 0.06, N))
    m, i = best_discrete_carbon(c_pert)
    # continuous relaxation: a real-weighted zero-carbon book always exists (kernel of c.w), cf. Part 1
    print(f"Perturbed (trial {trial}):       min |net carbon| = {m:.4f}   -> exact zero is no longer reachable with unit lots")

print("\nContinuous relaxation (Part 1): net carbon = 0 is always attainable with real weights.")
print("Discrete problem: you need a search over 2^(2N) states, and you accept the closest feasible book.")

"""This is the honest boundary of B-U here:

* **Continuous / relaxed problem:** a zero-net-carbon antipodal-symmetric hedge exists. B-U guarantees this, and it tells you the penalty target "net carbon = 0" isn't contradictory.
* **Discrete problem:** existence of an *exact* zero is not guaranteed. The QUBO penalty finds the *closest* feasible book, via a solver.

## Summary

* **Necessary for what?** B-U is what gives the *existence guarantee* in the continuous setting and the `Z₂` (long↔short) symmetry that structures the discrete problem (even terms ⇒ paired ground states; odd terms ⇒ symmetry breaking). It supplies the theoretical justification for the carbon-neutrality target and the cost-term decomposition.
* **Not necessary for the optimiser to run.** Remove B-U and the pipeline still works: Part 3b shows the penalty `A` alone drives net carbon down, and Part 3 shows plain classical annealing recovers the same optimum.
* **QUBO isn't finding the pairs.** The QUBO is a cost function. The pairs come from a *solver* (brute force, annealing, QAOA). On the symmetric problem the solver's choice within an antipodal pair is arbitrary; only the odd terms (tilt/carry) decide.
* **For linear exposures B-U is overkill.** Carbon `c·w` is linear, so "`f(w) = f(−w)`" is just `c·w = 0`, a kernel of a matrix. The theorem is only needed to say something non-trivial for nonlinear exposures (Part 1b).

## Optional: swap in QAOA as the solver
Copied from `antipodal_qaoa.py` (QUBO → Ising → PennyLane QAOA, 12 qubits). Same `Q`, different solver. Takes a minute or two on Colab CPU.
"""

!pip install -q pennylane

def qubo_to_ising(Q, offset):
    Qs = (Q + Q.T) / 2
    n = Q.shape[0]
    ones = np.ones(n)
    h = -0.5 * Qs @ ones
    J = {(i, j): 0.5 * Qs[i, j] for i in range(n) for j in range(i + 1, n) if abs(Qs[i, j]) > 1e-12}
    const = offset + 0.25 * (ones @ Qs @ ones + np.trace(Qs))
    return h, J, const

def ising_energy(bits, h, J, const):
    z = 1 - 2 * np.asarray(bits, float)
    return const + h @ z + sum(Jij * z[i] * z[j] for (i, j), Jij in J.items())

def run_qaoa(h, J, const, p=3, steps=120, lr=0.05, seed=0):
    import pennylane as qml
    from pennylane import numpy as pnp
    n = len(h)
    scale = max(np.abs(h).max(), max(abs(v) for v in J.values()))
    hs = h / scale
    Js = {k: v / scale for k, v in J.items()}
    dev = qml.device("default.qubit", wires=n)
    ops = [qml.PauliZ(i) for i in range(n)] + [qml.PauliZ(i) @ qml.PauliZ(j) for (i, j) in Js]
    coeffs = [float(c) for c in hs] + [float(c) for c in Js.values()]
    H = qml.dot(coeffs, ops)

    def ansatz(params):
        for i in range(n):
            qml.Hadamard(wires=i)
        for layer in range(p):
            gamma, beta = params[0][layer], params[1][layer]
            for i in range(n):
                qml.RZ(2 * gamma * hs[i], wires=i)
            for (i, j), Jij in Js.items():
                qml.IsingZZ(2 * gamma * Jij, wires=[i, j])
            for i in range(n):
                qml.RX(2 * beta, wires=i)

    @qml.qnode(dev, diff_method="backprop")
    def cost(params):
        ansatz(params)
        return qml.expval(H)

    @qml.qnode(dev)
    def probs(params):
        ansatz(params)
        return qml.probs(wires=range(n))

    rng = np.random.default_rng(seed)
    init = np.stack([np.linspace(0.1, 0.6, p), np.linspace(0.6, 0.1, p)])
    params = pnp.array(init + rng.normal(0, 0.02, init.shape), requires_grad=True)
    opt = qml.AdamOptimizer(stepsize=lr)
    for s in range(steps):
        params, c = opt.step_and_cost(cost, params)
        if s % 20 == 0:
            print(f"  step {s:3d}  <E> = {float(c) * scale + const:8.4f}")
    return np.array(probs(params))

# Ising conversion must reproduce the QUBO energy (sanity check, no quantum needed)
h, J, const = qubo_to_ising(Q_odd, off_odd)
assert np.isclose(ising_energy(ALL[i_opt], h, J, const), e_opt)
print("Ising/QUBO consistency check passed")

pr = run_qaoa(h, J, const)
top = np.argsort(pr)[::-1][:5]
print("\nTop QAOA samples (the solver's output, not the QUBO's):")
for idx in top:
    L, S, nc = decode(ALL[idx])
    print(f"  p={pr[idx]:.3f}  E={E_odd[idx]:7.3f}  long={L} short={S}  net_carbon={nc:+.3f}")
print(f"\nP(optimal bitstring) = {pr[i_opt]:.3f}   (uniform guess would be {1 / 2 ** n:.4f})")